# Generated by Django 4.1.3 on 2024-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieval_model', models.CharField(choices=[('boolean', 'Boolean Model'), ('extended_boolean', 'Extended Boolean Model'), ('vector', 'Vector Model')], max_length=20)),
                ('query', models.CharField(max_length=255)),
            ],
        ),
    ]
